import {
  BelongsTo,
  Column,
  DataType,
  ForeignKey,
  HasMany,
  Model,
  Table,
} from 'sequelize-typescript';
import { Organization } from './organization.model';
import { User } from './user.model';
import { ChatMessage } from './chat-message.model';

@Table({
  tableName: 'chat_threads',
  timestamps: true,
  indexes: [
    { fields: ['userId', 'lastMessageAt'] },
    { fields: ['organizationId'] },
  ],
})
export class ChatThread extends Model {
  @Column({
    type: DataType.UUID,
    defaultValue: DataType.UUIDV4,
    primaryKey: true,
  })
  declare id: string;

  @ForeignKey(() => Organization)
  @Column({ type: DataType.UUID, allowNull: false })
  declare organizationId: string;

  @BelongsTo(() => Organization)
  declare organization: Organization;

  @ForeignKey(() => User)
  @Column({ type: DataType.UUID, allowNull: false })
  declare userId: string;

  @BelongsTo(() => User)
  declare user: User;

  @Column({ type: DataType.STRING, allowNull: false, defaultValue: 'New chat' })
  declare title: string;

  @Column({ type: DataType.BOOLEAN, allowNull: false, defaultValue: true })
  declare titleAutoGenerated: boolean;

  @Column({ type: DataType.DATE, allowNull: false, defaultValue: DataType.NOW })
  declare lastMessageAt: Date;

  @HasMany(() => ChatMessage)
  declare messages: ChatMessage[];
}
